### PR TITLE
Create thumbnails for uploaded files (Video and Photo)

### PR DESCRIPTION
**Pull request by Schoumi**
Like the progress the data is sent threw callback in json: {"thumbnail":"/data/user/0/io.cozy.drive.mobile/cache/thumbs/video-1723994396.png"}

the thumbnail is store in the cache directory and is delete at the end of the upload.

### CODE REVIEW

**Comment by y-lohse** [comment]
Thanks! Everything looks ok, but I don't see where the thumbnail URL is sent to javascript?

**Comment by Schoumi** [comment]
https://github.com/cozy/cordova-plugin-list-library-items/pull/17/files#diff-948886ae2b0fcaf3ddc70c4c59104a97R525

Maybe not the right place now i think about it. Line 517 to 525 could be here: https://github.com/cozy/cordova-plugin-list-library-items/pull/17/files#diff-948886ae2b0fcaf3ddc70c4c59104a97R325 with checks that thumbs isn't null.

**Comment by y-lohse** [comment]
Ah yes, I really expected it to be over there. `createThumbnail` should probably just create a thumbnai land nothing else^^. Would you mind moving the code there? Otherwise it's all good for me!

**Comment by Schoumi** [comment]
Done

**Review by y-lohse — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
